use_frameworks!

platform :ios, '9.0'

target 'RmCollect_Example' do
  pod 'RMCollect', :path => '../'
    
end


post_install do |installer|
  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end